"$schema" = "./node_modules/wrangler/config-schema.json"

compatibility_date = "2026-07-11"

compatibility_flags = ["global_fetch_strictly_public", "nodejs_compat"]

name = "resuming-web"

main = "./sentry.server.config.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

    [observability.logs]
    head_sampling_rate = 1
    destinations = ["sentry-logs"]

    [observability.traces]
    enabled = true
    head_sampling_rate = 0.01
    destinations = ["sentry-traces"]

[version_metadata]
binding = "CF_VERSION_METADATA"

[env.staging]


[env.production]