// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_logs (user_id, type, message)
VALUES ($1, $2, $3)
RETURNING id, public_id, user_id, type, message, created_at, updated_at, expires_at
`

type CreateAdminAuditLogParams struct {
	UserID  int32  `json:"user_id"`
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog, arg.UserID, arg.Type, arg.Message)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAdminAuditLogsByUserId = `-- name: FindAdminAuditLogsByUserId :many
SELECT id, public_id, user_id, type, message, created_at, updated_at, expires_at FROM admin_audit_logs
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindAdminAuditLogsByUserId(ctx context.Context, userID int32) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, findAdminAuditLogsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllAdminAuditLogs = `-- name: FindAllAdminAuditLogs :many
SELECT id, public_id, user_id, type, message, created_at, updated_at, expires_at FROM admin_audit_logs
WHERE (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindAllAdminAuditLogs(ctx context.Context) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, findAllAdminAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminAuditLogByPublicId = `-- name: UpdateAdminAuditLogByPublicId :exec
UPDATE admin_audit_logs SET type = $1, message = $2, updated_at = NOW()
WHERE public_id = $3
`

type UpdateAdminAuditLogByPublicIdParams struct {
	Type     string      `json:"type"`
	Message  string      `json:"message"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateAdminAuditLogByPublicId(ctx context.Context, arg UpdateAdminAuditLogByPublicIdParams) error {
	_, err := q.db.Exec(ctx, updateAdminAuditLogByPublicId, arg.Type, arg.Message, arg.PublicID)
	return err
}
