// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ats.sql

package sqlc

import (
	"context"
)

const findAllAts = `-- name: FindAllAts :many
SELECT id, public_id, user_id, score, reasoning, created_at, updated_at, deleted_at, expires_at FROM ats
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllAts(ctx context.Context) ([]At, error) {
	rows, err := q.db.Query(ctx, findAllAts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []At
	for rows.Next() {
		var i At
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Score,
			&i.Reasoning,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAtsByUserId = `-- name: FindAtsByUserId :one
SELECT id, public_id, user_id, score, reasoning, created_at, updated_at, deleted_at, expires_at FROM ats
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindAtsByUserId(ctx context.Context, userID int32) (At, error) {
	row := q.db.QueryRow(ctx, findAtsByUserId, userID)
	var i At
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Score,
		&i.Reasoning,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateAts = `-- name: UpdateAts :exec
UPDATE ats SET
  score = $1,
  reasoning = $2,
  updated_at = NOW()
WHERE user_id = $3
`

type UpdateAtsParams struct {
	Score     int32  `json:"score"`
	Reasoning string `json:"reasoning"`
	UserID    int32  `json:"user_id"`
}

func (q *Queries) UpdateAts(ctx context.Context, arg UpdateAtsParams) error {
	_, err := q.db.Exec(ctx, updateAts, arg.Score, arg.Reasoning, arg.UserID)
	return err
}

const upsertAts = `-- name: UpsertAts :one
INSERT INTO ats (user_id, score, reasoning)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) WHERE (expires_at IS NULL OR expires_at > NOW())
DO UPDATE SET score = $2, reasoning = $3, updated_at = NOW()
RETURNING id, public_id, user_id, score, reasoning, created_at, updated_at, deleted_at, expires_at
`

type UpsertAtsParams struct {
	UserID    int32  `json:"user_id"`
	Score     int32  `json:"score"`
	Reasoning string `json:"reasoning"`
}

func (q *Queries) UpsertAts(ctx context.Context, arg UpsertAtsParams) (At, error) {
	row := q.db.QueryRow(ctx, upsertAts, arg.UserID, arg.Score, arg.Reasoning)
	var i At
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Score,
		&i.Reasoning,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
