// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_report_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClientReportLog = `-- name: CreateClientReportLog :one
INSERT INTO client_report_logs (reporting_user_id, target_user_id, type)
VALUES ($1, $2, $3)
RETURNING id, public_id, reporting_user_id, target_user_id, type, created_at, updated_at, expires_at
`

type CreateClientReportLogParams struct {
	ReportingUserID int32  `json:"reporting_user_id"`
	TargetUserID    int32  `json:"target_user_id"`
	Type            string `json:"type"`
}

func (q *Queries) CreateClientReportLog(ctx context.Context, arg CreateClientReportLogParams) (ClientReportLog, error) {
	row := q.db.QueryRow(ctx, createClientReportLog, arg.ReportingUserID, arg.TargetUserID, arg.Type)
	var i ClientReportLog
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ReportingUserID,
		&i.TargetUserID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAllClientReportLogs = `-- name: FindAllClientReportLogs :many
SELECT id, public_id, reporting_user_id, target_user_id, type, created_at, updated_at, expires_at FROM client_report_logs
WHERE (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindAllClientReportLogs(ctx context.Context) ([]ClientReportLog, error) {
	rows, err := q.db.Query(ctx, findAllClientReportLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientReportLog
	for rows.Next() {
		var i ClientReportLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ReportingUserID,
			&i.TargetUserID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClientReportLogByPublicId = `-- name: FindClientReportLogByPublicId :one
SELECT id, public_id, reporting_user_id, target_user_id, type, created_at, updated_at, expires_at FROM client_report_logs
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) FindClientReportLogByPublicId(ctx context.Context, publicID pgtype.UUID) (ClientReportLog, error) {
	row := q.db.QueryRow(ctx, findClientReportLogByPublicId, publicID)
	var i ClientReportLog
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ReportingUserID,
		&i.TargetUserID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findClientReportLogWithUsers = `-- name: FindClientReportLogWithUsers :many
SELECT crl.id, crl.public_id, crl.reporting_user_id, crl.target_user_id, crl.type, crl.created_at, crl.updated_at, crl.expires_at, ru.public_id as reporting_user_public_id, tu.public_id as target_user_public_id
FROM client_report_logs crl
JOIN users ru ON ru.id = crl.reporting_user_id
JOIN users tu ON tu.id = crl.target_user_id
WHERE (crl.expires_at IS NULL OR crl.expires_at > NOW())
ORDER BY crl.created_at DESC
`

type FindClientReportLogWithUsersRow struct {
	ID                    int32              `json:"id"`
	PublicID              pgtype.UUID        `json:"public_id"`
	ReportingUserID       int32              `json:"reporting_user_id"`
	TargetUserID          int32              `json:"target_user_id"`
	Type                  string             `json:"type"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ReportingUserPublicID pgtype.UUID        `json:"reporting_user_public_id"`
	TargetUserPublicID    pgtype.UUID        `json:"target_user_public_id"`
}

func (q *Queries) FindClientReportLogWithUsers(ctx context.Context) ([]FindClientReportLogWithUsersRow, error) {
	rows, err := q.db.Query(ctx, findClientReportLogWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindClientReportLogWithUsersRow
	for rows.Next() {
		var i FindClientReportLogWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ReportingUserID,
			&i.TargetUserID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ReportingUserPublicID,
			&i.TargetUserPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientReportLogByPublicId = `-- name: UpdateClientReportLogByPublicId :exec
UPDATE client_report_logs SET type = $1, updated_at = NOW()
WHERE public_id = $2
`

type UpdateClientReportLogByPublicIdParams struct {
	Type     string      `json:"type"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateClientReportLogByPublicId(ctx context.Context, arg UpdateClientReportLogByPublicIdParams) error {
	_, err := q.db.Exec(ctx, updateClientReportLogByPublicId, arg.Type, arg.PublicID)
	return err
}
