// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_support_messaging.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClientSupportMessage = `-- name: CreateClientSupportMessage :one
INSERT INTO client_support_messaging (type, content)
VALUES ($1, $2)
RETURNING id, public_id, type, content, created_at, updated_at, expires_at
`

type CreateClientSupportMessageParams struct {
	Type    string `json:"type"`
	Content []byte `json:"content"`
}

func (q *Queries) CreateClientSupportMessage(ctx context.Context, arg CreateClientSupportMessageParams) (ClientSupportMessaging, error) {
	row := q.db.QueryRow(ctx, createClientSupportMessage, arg.Type, arg.Content)
	var i ClientSupportMessaging
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAllClientSupportMessages = `-- name: FindAllClientSupportMessages :many
SELECT id, public_id, type, content, created_at, updated_at, expires_at FROM client_support_messaging
WHERE (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindAllClientSupportMessages(ctx context.Context) ([]ClientSupportMessaging, error) {
	rows, err := q.db.Query(ctx, findAllClientSupportMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientSupportMessaging
	for rows.Next() {
		var i ClientSupportMessaging
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClientSupportMessageByPublicId = `-- name: FindClientSupportMessageByPublicId :one
SELECT id, public_id, type, content, created_at, updated_at, expires_at FROM client_support_messaging
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) FindClientSupportMessageByPublicId(ctx context.Context, publicID pgtype.UUID) (ClientSupportMessaging, error) {
	row := q.db.QueryRow(ctx, findClientSupportMessageByPublicId, publicID)
	var i ClientSupportMessaging
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateClientSupportMessageByPublicId = `-- name: UpdateClientSupportMessageByPublicId :exec
UPDATE client_support_messaging SET type = $1, content = $2, updated_at = NOW()
WHERE public_id = $3
`

type UpdateClientSupportMessageByPublicIdParams struct {
	Type     string      `json:"type"`
	Content  []byte      `json:"content"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateClientSupportMessageByPublicId(ctx context.Context, arg UpdateClientSupportMessageByPublicIdParams) error {
	_, err := q.db.Exec(ctx, updateClientSupportMessageByPublicId, arg.Type, arg.Content, arg.PublicID)
	return err
}
