// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClientAuditLog = `-- name: CreateClientAuditLog :one
INSERT INTO client_audit_logs (user_id, type, message)
VALUES ($1, $2, $3)
RETURNING id, public_id, user_id, type, message, created_at, updated_at, expires_at
`

type CreateClientAuditLogParams struct {
	UserID  int32  `json:"user_id"`
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) CreateClientAuditLog(ctx context.Context, arg CreateClientAuditLogParams) (ClientAuditLog, error) {
	row := q.db.QueryRow(ctx, createClientAuditLog, arg.UserID, arg.Type, arg.Message)
	var i ClientAuditLog
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAllClientAuditLogs = `-- name: FindAllClientAuditLogs :many
SELECT id, public_id, user_id, type, message, created_at, updated_at, expires_at FROM client_audit_logs
WHERE (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindAllClientAuditLogs(ctx context.Context) ([]ClientAuditLog, error) {
	rows, err := q.db.Query(ctx, findAllClientAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientAuditLog
	for rows.Next() {
		var i ClientAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClientAuditLogsByUserId = `-- name: FindClientAuditLogsByUserId :many
SELECT id, public_id, user_id, type, message, created_at, updated_at, expires_at FROM client_audit_logs
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindClientAuditLogsByUserId(ctx context.Context, userID int32) ([]ClientAuditLog, error) {
	rows, err := q.db.Query(ctx, findClientAuditLogsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientAuditLog
	for rows.Next() {
		var i ClientAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientAuditLogByPublicId = `-- name: UpdateClientAuditLogByPublicId :exec
UPDATE client_audit_logs SET type = $1, message = $2, updated_at = NOW()
WHERE public_id = $3
`

type UpdateClientAuditLogByPublicIdParams struct {
	Type     string      `json:"type"`
	Message  string      `json:"message"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateClientAuditLogByPublicId(ctx context.Context, arg UpdateClientAuditLogByPublicIdParams) error {
	_, err := q.db.Exec(ctx, updateClientAuditLogByPublicId, arg.Type, arg.Message, arg.PublicID)
	return err
}
