// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: error_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createErrorLog = `-- name: CreateErrorLog :one
INSERT INTO error_logs (user_id, type, message)
VALUES ($1, $2, $3)
RETURNING id, public_id, user_id, type, message, created_at, updated_at, expires_at
`

type CreateErrorLogParams struct {
	UserID  int32  `json:"user_id"`
	Type    int32  `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) CreateErrorLog(ctx context.Context, arg CreateErrorLogParams) (ErrorLog, error) {
	row := q.db.QueryRow(ctx, createErrorLog, arg.UserID, arg.Type, arg.Message)
	var i ErrorLog
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAllErrorLogs = `-- name: FindAllErrorLogs :many
SELECT id, public_id, user_id, type, message, created_at, updated_at, expires_at FROM error_logs
WHERE (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindAllErrorLogs(ctx context.Context) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, findAllErrorLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorLog
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateErrorLogByPublicId = `-- name: UpdateErrorLogByPublicId :exec
UPDATE error_logs SET type = $1, message = $2, updated_at = NOW()
WHERE public_id = $3
`

type UpdateErrorLogByPublicIdParams struct {
	Type     int32       `json:"type"`
	Message  string      `json:"message"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateErrorLogByPublicId(ctx context.Context, arg UpdateErrorLogByPublicIdParams) error {
	_, err := q.db.Exec(ctx, updateErrorLogByPublicId, arg.Type, arg.Message, arg.PublicID)
	return err
}
