// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jwt_keys.sql

package sqlc

import (
	"context"
)

const createJwtKey = `-- name: CreateJwtKey :one
INSERT INTO jwt_keys (user_id, key)
VALUES ($1, $2)
RETURNING id, public_id, user_id, key, created_at, updated_at, expires_at
`

type CreateJwtKeyParams struct {
	UserID int32  `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) CreateJwtKey(ctx context.Context, arg CreateJwtKeyParams) (JwtKey, error) {
	row := q.db.QueryRow(ctx, createJwtKey, arg.UserID, arg.Key)
	var i JwtKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteJwtKeyByUserId = `-- name: DeleteJwtKeyByUserId :exec
DELETE FROM jwt_keys WHERE user_id = $1
`

func (q *Queries) DeleteJwtKeyByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteJwtKeyByUserId, userID)
	return err
}

const findAllJwtKeys = `-- name: FindAllJwtKeys :many
SELECT id, public_id, user_id, key, created_at, updated_at, expires_at FROM jwt_keys
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllJwtKeys(ctx context.Context) ([]JwtKey, error) {
	rows, err := q.db.Query(ctx, findAllJwtKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JwtKey
	for rows.Next() {
		var i JwtKey
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findJwtKeyByUserId = `-- name: FindJwtKeyByUserId :one
SELECT id, public_id, user_id, key, created_at, updated_at, expires_at FROM jwt_keys
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindJwtKeyByUserId(ctx context.Context, userID int32) (JwtKey, error) {
	row := q.db.QueryRow(ctx, findJwtKeyByUserId, userID)
	var i JwtKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateJwtKey = `-- name: UpdateJwtKey :exec
UPDATE jwt_keys SET key = $1, updated_at = NOW()
WHERE user_id = $2
`

type UpdateJwtKeyParams struct {
	Key    string `json:"key"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) UpdateJwtKey(ctx context.Context, arg UpdateJwtKeyParams) error {
	_, err := q.db.Exec(ctx, updateJwtKey, arg.Key, arg.UserID)
	return err
}
