// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserType string

const (
	UserTypeSuperAdmin UserType = "super-admin"
	UserTypeAdmin      UserType = "admin"
	UserTypeClient     UserType = "client"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type NullUserType struct {
	UserType UserType `json:"user_type"`
	Valid    bool     `json:"valid"` // Valid is true if UserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserType) Scan(value interface{}) error {
	if value == nil {
		ns.UserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserType), nil
}

type AdminAuditLog struct {
	ID        int32              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	UserID    int32              `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type At struct {
	ID        int32              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	UserID    int32              `json:"user_id"`
	Score     int32              `json:"score"`
	Reasoning string             `json:"reasoning"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ClientAuditLog struct {
	ID        int32              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	UserID    int32              `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ClientReportLog struct {
	ID              int32              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	ReportingUserID int32              `json:"reporting_user_id"`
	TargetUserID    int32              `json:"target_user_id"`
	Type            string             `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type ClientSupportMessaging struct {
	ID        int32              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Type      string             `json:"type"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ErrorLog struct {
	ID        int32              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	UserID    int32              `json:"user_id"`
	Type      int32              `json:"type"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type JwtKey struct {
	ID        int32              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	UserID    int32              `json:"user_id"`
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Portfolio struct {
	ID         int32              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	UserID     int32              `json:"user_id"`
	TemplateID int32              `json:"template_id"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type Resume struct {
	ID         int32              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	UserID     int32              `json:"user_id"`
	TemplateID int32              `json:"template_id"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type Session struct {
	ID         int32              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	UserID     int32              `json:"user_id"`
	SessionKey string             `json:"session_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type ShowcaseRecord struct {
	ID            int32              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	UserID        int32              `json:"user_id"`
	Name          []string           `json:"name"`
	Email         []string           `json:"email"`
	PhoneNumber   []string           `json:"phone_number"`
	Address       []string           `json:"address"`
	SocialMedia   []string           `json:"social_media"`
	JobExperience []byte             `json:"job_experience"`
	Education     []byte             `json:"education"`
	Skill         []string           `json:"skill"`
	Certificate   []byte             `json:"certificate"`
	Language      []string           `json:"language"`
	Project       []byte             `json:"project"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID          int32              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Password    []byte             `json:"password"`
	Displayname string             `json:"displayname"`
	UserType    UserType           `json:"user_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BannedAt    pgtype.Timestamptz `json:"banned_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}
