// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolios.sql

package sqlc

import (
	"context"
)

const findAllPortfolios = `-- name: FindAllPortfolios :many
SELECT id, public_id, user_id, template_id, detail, created_at, updated_at, deleted_at, expires_at FROM portfolios
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllPortfolios(ctx context.Context) ([]Portfolio, error) {
	rows, err := q.db.Query(ctx, findAllPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Portfolio
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.TemplateID,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPortfolioByUserId = `-- name: FindPortfolioByUserId :one
SELECT id, public_id, user_id, template_id, detail, created_at, updated_at, deleted_at, expires_at FROM portfolios
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindPortfolioByUserId(ctx context.Context, userID int32) (Portfolio, error) {
	row := q.db.QueryRow(ctx, findPortfolioByUserId, userID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TemplateID,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updatePortfolio = `-- name: UpdatePortfolio :exec
UPDATE portfolios SET
  template_id = $1,
  detail = $2,
  updated_at = NOW()
WHERE user_id = $3
`

type UpdatePortfolioParams struct {
	TemplateID int32  `json:"template_id"`
	Detail     []byte `json:"detail"`
	UserID     int32  `json:"user_id"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) error {
	_, err := q.db.Exec(ctx, updatePortfolio, arg.TemplateID, arg.Detail, arg.UserID)
	return err
}

const upsertPortfolio = `-- name: UpsertPortfolio :one
INSERT INTO portfolios (user_id, template_id, detail)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) WHERE (expires_at IS NULL OR expires_at > NOW())
DO UPDATE SET template_id = $2, detail = $3, updated_at = NOW()
RETURNING id, public_id, user_id, template_id, detail, created_at, updated_at, deleted_at, expires_at
`

type UpsertPortfolioParams struct {
	UserID     int32  `json:"user_id"`
	TemplateID int32  `json:"template_id"`
	Detail     []byte `json:"detail"`
}

func (q *Queries) UpsertPortfolio(ctx context.Context, arg UpsertPortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, upsertPortfolio, arg.UserID, arg.TemplateID, arg.Detail)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TemplateID,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
