// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsersByType(ctx context.Context, userType UserType) (int64, error)
	CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error)
	CreateClientAuditLog(ctx context.Context, arg CreateClientAuditLogParams) (ClientAuditLog, error)
	CreateClientReportLog(ctx context.Context, arg CreateClientReportLogParams) (ClientReportLog, error)
	CreateClientSupportMessage(ctx context.Context, arg CreateClientSupportMessageParams) (ClientSupportMessaging, error)
	CreateErrorLog(ctx context.Context, arg CreateErrorLogParams) (ErrorLog, error)
	CreateJwtKey(ctx context.Context, arg CreateJwtKeyParams) (JwtKey, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShowcaseRecord(ctx context.Context, userID int32) (ShowcaseRecord, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllSessions(ctx context.Context) error
	DeleteJwtKeyByUserId(ctx context.Context, userID int32) error
	DeleteSessionByUserId(ctx context.Context, userID int32) error
	FindAdminAuditLogsByUserId(ctx context.Context, userID int32) ([]AdminAuditLog, error)
	FindAllAdminAuditLogs(ctx context.Context) ([]AdminAuditLog, error)
	FindAllAdminsWithSession(ctx context.Context) ([]FindAllAdminsWithSessionRow, error)
	FindAllAts(ctx context.Context) ([]At, error)
	FindAllClientAuditLogs(ctx context.Context) ([]ClientAuditLog, error)
	FindAllClientReportLogs(ctx context.Context) ([]ClientReportLog, error)
	FindAllClientSupportMessages(ctx context.Context) ([]ClientSupportMessaging, error)
	FindAllClientsWithSession(ctx context.Context) ([]FindAllClientsWithSessionRow, error)
	FindAllErrorLogs(ctx context.Context) ([]ErrorLog, error)
	FindAllJwtKeys(ctx context.Context) ([]JwtKey, error)
	FindAllPortfolios(ctx context.Context) ([]Portfolio, error)
	FindAllResumes(ctx context.Context) ([]Resume, error)
	FindAllSessions(ctx context.Context) ([]Session, error)
	FindAllSessionsWithUser(ctx context.Context) ([]FindAllSessionsWithUserRow, error)
	FindAllShowcaseRecords(ctx context.Context) ([]ShowcaseRecord, error)
	FindAllUsers(ctx context.Context) ([]User, error)
	FindAllUsersByType(ctx context.Context, userType UserType) ([]User, error)
	FindAtsByUserId(ctx context.Context, userID int32) (At, error)
	FindClientAuditLogsByUserId(ctx context.Context, userID int32) ([]ClientAuditLog, error)
	FindClientReportLogByPublicId(ctx context.Context, publicID pgtype.UUID) (ClientReportLog, error)
	FindClientReportLogWithUsers(ctx context.Context) ([]FindClientReportLogWithUsersRow, error)
	FindClientSupportMessageByPublicId(ctx context.Context, publicID pgtype.UUID) (ClientSupportMessaging, error)
	FindJwtKeyByUserId(ctx context.Context, userID int32) (JwtKey, error)
	FindPortfolioByUserId(ctx context.Context, userID int32) (Portfolio, error)
	FindResumeByUserId(ctx context.Context, userID int32) (Resume, error)
	FindSessionByPublicId(ctx context.Context, publicID pgtype.UUID) (Session, error)
	FindSessionByUserId(ctx context.Context, userID int32) (Session, error)
	FindShowcaseRecordByPublicId(ctx context.Context, publicID pgtype.UUID) (ShowcaseRecord, error)
	FindShowcaseRecordByUserId(ctx context.Context, userID int32) (ShowcaseRecord, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByEmailWithExpired(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id int32) (User, error)
	FindUserByPublicId(ctx context.Context, publicID pgtype.UUID) (User, error)
	FindUserByPublicIdWithSession(ctx context.Context, publicID pgtype.UUID) (FindUserByPublicIdWithSessionRow, error)
	HardDeleteExpiredUsers(ctx context.Context) error
	SoftDeleteUser(ctx context.Context, id int32) error
	UpdateAdminAuditLogByPublicId(ctx context.Context, arg UpdateAdminAuditLogByPublicIdParams) error
	UpdateAts(ctx context.Context, arg UpdateAtsParams) error
	UpdateClientAuditLogByPublicId(ctx context.Context, arg UpdateClientAuditLogByPublicIdParams) error
	UpdateClientReportLogByPublicId(ctx context.Context, arg UpdateClientReportLogByPublicIdParams) error
	UpdateClientSupportMessageByPublicId(ctx context.Context, arg UpdateClientSupportMessageByPublicIdParams) error
	UpdateErrorLogByPublicId(ctx context.Context, arg UpdateErrorLogByPublicIdParams) error
	UpdateJwtKey(ctx context.Context, arg UpdateJwtKeyParams) error
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) error
	UpdateResume(ctx context.Context, arg UpdateResumeParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateShowcaseRecord(ctx context.Context, arg UpdateShowcaseRecordParams) error
	UpdateShowcaseRecordByPublicId(ctx context.Context, arg UpdateShowcaseRecordByPublicIdParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserByPublicId(ctx context.Context, arg UpdateUserByPublicIdParams) (User, error)
	UpsertAts(ctx context.Context, arg UpsertAtsParams) (At, error)
	UpsertPortfolio(ctx context.Context, arg UpsertPortfolioParams) (Portfolio, error)
	UpsertResume(ctx context.Context, arg UpsertResumeParams) (Resume, error)
}

var _ Querier = (*Queries)(nil)
