// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resumes.sql

package sqlc

import (
	"context"
)

const findAllResumes = `-- name: FindAllResumes :many
SELECT id, public_id, user_id, template_id, detail, created_at, updated_at, deleted_at, expires_at FROM resumes
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllResumes(ctx context.Context) ([]Resume, error) {
	rows, err := q.db.Query(ctx, findAllResumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resume
	for rows.Next() {
		var i Resume
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.TemplateID,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResumeByUserId = `-- name: FindResumeByUserId :one
SELECT id, public_id, user_id, template_id, detail, created_at, updated_at, deleted_at, expires_at FROM resumes
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindResumeByUserId(ctx context.Context, userID int32) (Resume, error) {
	row := q.db.QueryRow(ctx, findResumeByUserId, userID)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TemplateID,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateResume = `-- name: UpdateResume :exec
UPDATE resumes SET
  template_id = $1,
  detail = $2,
  updated_at = NOW()
WHERE user_id = $3
`

type UpdateResumeParams struct {
	TemplateID int32  `json:"template_id"`
	Detail     []byte `json:"detail"`
	UserID     int32  `json:"user_id"`
}

func (q *Queries) UpdateResume(ctx context.Context, arg UpdateResumeParams) error {
	_, err := q.db.Exec(ctx, updateResume, arg.TemplateID, arg.Detail, arg.UserID)
	return err
}

const upsertResume = `-- name: UpsertResume :one
INSERT INTO resumes (user_id, template_id, detail)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) WHERE (expires_at IS NULL OR expires_at > NOW())
DO UPDATE SET template_id = $2, detail = $3, updated_at = NOW()
RETURNING id, public_id, user_id, template_id, detail, created_at, updated_at, deleted_at, expires_at
`

type UpsertResumeParams struct {
	UserID     int32  `json:"user_id"`
	TemplateID int32  `json:"template_id"`
	Detail     []byte `json:"detail"`
}

func (q *Queries) UpsertResume(ctx context.Context, arg UpsertResumeParams) (Resume, error) {
	row := q.db.QueryRow(ctx, upsertResume, arg.UserID, arg.TemplateID, arg.Detail)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TemplateID,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
