// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_key)
VALUES ($1, $2)
RETURNING id, public_id, user_id, session_key, created_at, updated_at, expires_at
`

type CreateSessionParams struct {
	UserID     int32  `json:"user_id"`
	SessionKey string `json:"session_key"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.SessionKey)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.SessionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM sessions
`

func (q *Queries) DeleteAllSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllSessions)
	return err
}

const deleteSessionByUserId = `-- name: DeleteSessionByUserId :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionByUserId, userID)
	return err
}

const findAllSessions = `-- name: FindAllSessions :many
SELECT id, public_id, user_id, session_key, created_at, updated_at, expires_at FROM sessions
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, findAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.SessionKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllSessionsWithUser = `-- name: FindAllSessionsWithUser :many
SELECT s.id, s.public_id, s.user_id, s.session_key, s.created_at, s.updated_at, s.expires_at, u.public_id as user_public_id, u.username, u.displayname, u.user_type
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE (s.expires_at IS NULL OR s.expires_at > NOW())
`

type FindAllSessionsWithUserRow struct {
	ID           int32              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	UserID       int32              `json:"user_id"`
	SessionKey   string             `json:"session_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UserPublicID pgtype.UUID        `json:"user_public_id"`
	Username     string             `json:"username"`
	Displayname  string             `json:"displayname"`
	UserType     UserType           `json:"user_type"`
}

func (q *Queries) FindAllSessionsWithUser(ctx context.Context) ([]FindAllSessionsWithUserRow, error) {
	rows, err := q.db.Query(ctx, findAllSessionsWithUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllSessionsWithUserRow
	for rows.Next() {
		var i FindAllSessionsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.SessionKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.UserPublicID,
			&i.Username,
			&i.Displayname,
			&i.UserType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionByPublicId = `-- name: FindSessionByPublicId :one
SELECT id, public_id, user_id, session_key, created_at, updated_at, expires_at FROM sessions
WHERE public_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindSessionByPublicId(ctx context.Context, publicID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByPublicId, publicID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.SessionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findSessionByUserId = `-- name: FindSessionByUserId :one
SELECT id, public_id, user_id, session_key, created_at, updated_at, expires_at FROM sessions
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindSessionByUserId(ctx context.Context, userID int32) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByUserId, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.SessionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions SET session_key = $1, updated_at = NOW()
WHERE user_id = $2
`

type UpdateSessionParams struct {
	SessionKey string `json:"session_key"`
	UserID     int32  `json:"user_id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession, arg.SessionKey, arg.UserID)
	return err
}
