// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: showcase_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShowcaseRecord = `-- name: CreateShowcaseRecord :one
INSERT INTO showcase_records (user_id)
VALUES ($1)
RETURNING id, public_id, user_id, name, email, phone_number, address, social_media, job_experience, education, skill, certificate, language, project, created_at, updated_at, deleted_at, expires_at
`

func (q *Queries) CreateShowcaseRecord(ctx context.Context, userID int32) (ShowcaseRecord, error) {
	row := q.db.QueryRow(ctx, createShowcaseRecord, userID)
	var i ShowcaseRecord
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.SocialMedia,
		&i.JobExperience,
		&i.Education,
		&i.Skill,
		&i.Certificate,
		&i.Language,
		&i.Project,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAllShowcaseRecords = `-- name: FindAllShowcaseRecords :many
SELECT id, public_id, user_id, name, email, phone_number, address, social_media, job_experience, education, skill, certificate, language, project, created_at, updated_at, deleted_at, expires_at FROM showcase_records
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllShowcaseRecords(ctx context.Context) ([]ShowcaseRecord, error) {
	rows, err := q.db.Query(ctx, findAllShowcaseRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowcaseRecord
	for rows.Next() {
		var i ShowcaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.Address,
			&i.SocialMedia,
			&i.JobExperience,
			&i.Education,
			&i.Skill,
			&i.Certificate,
			&i.Language,
			&i.Project,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findShowcaseRecordByPublicId = `-- name: FindShowcaseRecordByPublicId :one
SELECT id, public_id, user_id, name, email, phone_number, address, social_media, job_experience, education, skill, certificate, language, project, created_at, updated_at, deleted_at, expires_at FROM showcase_records
WHERE public_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindShowcaseRecordByPublicId(ctx context.Context, publicID pgtype.UUID) (ShowcaseRecord, error) {
	row := q.db.QueryRow(ctx, findShowcaseRecordByPublicId, publicID)
	var i ShowcaseRecord
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.SocialMedia,
		&i.JobExperience,
		&i.Education,
		&i.Skill,
		&i.Certificate,
		&i.Language,
		&i.Project,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findShowcaseRecordByUserId = `-- name: FindShowcaseRecordByUserId :one
SELECT id, public_id, user_id, name, email, phone_number, address, social_media, job_experience, education, skill, certificate, language, project, created_at, updated_at, deleted_at, expires_at FROM showcase_records
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindShowcaseRecordByUserId(ctx context.Context, userID int32) (ShowcaseRecord, error) {
	row := q.db.QueryRow(ctx, findShowcaseRecordByUserId, userID)
	var i ShowcaseRecord
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.SocialMedia,
		&i.JobExperience,
		&i.Education,
		&i.Skill,
		&i.Certificate,
		&i.Language,
		&i.Project,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateShowcaseRecord = `-- name: UpdateShowcaseRecord :exec
UPDATE showcase_records SET
  name = $1,
  email = $2,
  phone_number = $3,
  address = $4,
  social_media = $5,
  job_experience = $6,
  education = $7,
  skill = $8,
  certificate = $9,
  language = $10,
  project = $11,
  updated_at = NOW()
WHERE user_id = $12
`

type UpdateShowcaseRecordParams struct {
	Name          []string `json:"name"`
	Email         []string `json:"email"`
	PhoneNumber   []string `json:"phone_number"`
	Address       []string `json:"address"`
	SocialMedia   []string `json:"social_media"`
	JobExperience []byte   `json:"job_experience"`
	Education     []byte   `json:"education"`
	Skill         []string `json:"skill"`
	Certificate   []byte   `json:"certificate"`
	Language      []string `json:"language"`
	Project       []byte   `json:"project"`
	UserID        int32    `json:"user_id"`
}

func (q *Queries) UpdateShowcaseRecord(ctx context.Context, arg UpdateShowcaseRecordParams) error {
	_, err := q.db.Exec(ctx, updateShowcaseRecord,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
		arg.SocialMedia,
		arg.JobExperience,
		arg.Education,
		arg.Skill,
		arg.Certificate,
		arg.Language,
		arg.Project,
		arg.UserID,
	)
	return err
}

const updateShowcaseRecordByPublicId = `-- name: UpdateShowcaseRecordByPublicId :exec
UPDATE showcase_records SET
  name = $1,
  email = $2,
  phone_number = $3,
  address = $4,
  social_media = $5,
  job_experience = $6,
  education = $7,
  skill = $8,
  certificate = $9,
  language = $10,
  project = $11,
  updated_at = NOW()
WHERE public_id = $12
`

type UpdateShowcaseRecordByPublicIdParams struct {
	Name          []string    `json:"name"`
	Email         []string    `json:"email"`
	PhoneNumber   []string    `json:"phone_number"`
	Address       []string    `json:"address"`
	SocialMedia   []string    `json:"social_media"`
	JobExperience []byte      `json:"job_experience"`
	Education     []byte      `json:"education"`
	Skill         []string    `json:"skill"`
	Certificate   []byte      `json:"certificate"`
	Language      []string    `json:"language"`
	Project       []byte      `json:"project"`
	PublicID      pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateShowcaseRecordByPublicId(ctx context.Context, arg UpdateShowcaseRecordByPublicIdParams) error {
	_, err := q.db.Exec(ctx, updateShowcaseRecordByPublicId,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
		arg.SocialMedia,
		arg.JobExperience,
		arg.Education,
		arg.Skill,
		arg.Certificate,
		arg.Language,
		arg.Project,
		arg.PublicID,
	)
	return err
}
