// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByType = `-- name: CountUsersByType :one
SELECT COUNT(*) FROM users
WHERE user_type = $1::user_type
`

func (q *Queries) CountUsersByType(ctx context.Context, userType UserType) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByType, userType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password, displayname, user_type)
VALUES ($1, $2, $3, $4, $5::user_type)
RETURNING id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at
`

type CreateUserParams struct {
	Username    string   `json:"username"`
	Email       string   `json:"email"`
	Password    []byte   `json:"password"`
	Displayname string   `json:"displayname"`
	UserType    UserType `json:"user_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Displayname,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at FROM users
WHERE (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, findAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Displayname,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BannedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllUsersByType = `-- name: FindAllUsersByType :many
SELECT id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at FROM users
WHERE user_type = $1::user_type AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) FindAllUsersByType(ctx context.Context, userType UserType) ([]User, error) {
	rows, err := q.db.Query(ctx, findAllUsersByType, userType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Displayname,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BannedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at FROM users
WHERE email = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at FROM users
WHERE id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findUserByPublicId = `-- name: FindUserByPublicId :one
SELECT id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at FROM users
WHERE public_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) LIMIT 1
`

func (q *Queries) FindUserByPublicId(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPublicId, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const hardDeleteExpiredUsers = `-- name: HardDeleteExpiredUsers :exec
DELETE FROM users WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) HardDeleteExpiredUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredUsers)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET 
    username = $1, 
    email = $2, 
    displayname = $3, 
    password = $4, 
    user_type = $5::user_type, 
    banned_at = $6, 
    deleted_at = $7, 
    updated_at = NOW()
WHERE id = $8
`

type UpdateUserParams struct {
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Displayname string             `json:"displayname"`
	Password    []byte             `json:"password"`
	UserType    UserType           `json:"user_type"`
	BannedAt    pgtype.Timestamptz `json:"banned_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ID          int32              `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Displayname,
		arg.Password,
		arg.UserType,
		arg.BannedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}

const updateUserByPublicId = `-- name: UpdateUserByPublicId :one
UPDATE users SET 
    username = $1, 
    email = $2, 
    displayname = $3, 
    user_type = $4::user_type, 
    banned_at = $5, 
    deleted_at = $6, 
    updated_at = NOW()
WHERE public_id = $7
RETURNING id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at
`

type UpdateUserByPublicIdParams struct {
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Displayname string             `json:"displayname"`
	UserType    UserType           `json:"user_type"`
	BannedAt    pgtype.Timestamptz `json:"banned_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	PublicID    pgtype.UUID        `json:"public_id"`
}

func (q *Queries) UpdateUserByPublicId(ctx context.Context, arg UpdateUserByPublicIdParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserByPublicId,
		arg.Username,
		arg.Email,
		arg.Displayname,
		arg.UserType,
		arg.BannedAt,
		arg.DeletedAt,
		arg.PublicID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
