// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAllAdminsWithSession = `-- name: FindAllAdminsWithSession :many
SELECT u.id, u.public_id, u.username, u.email, u.password, u.displayname, u.user_type, u.created_at, u.updated_at, u.banned_at, u.deleted_at, u.expires_at, s.id as session_id, s.public_id as session_public_id, s.session_key, s.expires_at as session_expires_at
FROM users u
LEFT JOIN sessions s ON s.user_id = u.id AND (s.expires_at IS NULL OR s.expires_at > NOW())
WHERE u.user_type IN ('admin'::user_type, 'super-admin'::user_type) AND (u.expires_at IS NULL OR u.expires_at > NOW())
`

type FindAllAdminsWithSessionRow struct {
	ID               int32              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Password         []byte             `json:"password"`
	Displayname      string             `json:"displayname"`
	UserType         UserType           `json:"user_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BannedAt         pgtype.Timestamptz `json:"banned_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SessionID        pgtype.Int4        `json:"session_id"`
	SessionPublicID  pgtype.UUID        `json:"session_public_id"`
	SessionKey       pgtype.Text        `json:"session_key"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
}

func (q *Queries) FindAllAdminsWithSession(ctx context.Context) ([]FindAllAdminsWithSessionRow, error) {
	rows, err := q.db.Query(ctx, findAllAdminsWithSession)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllAdminsWithSessionRow
	for rows.Next() {
		var i FindAllAdminsWithSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Displayname,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BannedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.SessionPublicID,
			&i.SessionKey,
			&i.SessionExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllClientsWithSession = `-- name: FindAllClientsWithSession :many
SELECT u.id, u.public_id, u.username, u.email, u.password, u.displayname, u.user_type, u.created_at, u.updated_at, u.banned_at, u.deleted_at, u.expires_at, s.id as session_id, s.public_id as session_public_id, s.session_key, s.expires_at as session_expires_at
FROM users u
LEFT JOIN sessions s ON s.user_id = u.id AND (s.expires_at IS NULL OR s.expires_at > NOW())
WHERE u.user_type = 'client'::user_type AND (u.expires_at IS NULL OR u.expires_at > NOW())
`

type FindAllClientsWithSessionRow struct {
	ID               int32              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Password         []byte             `json:"password"`
	Displayname      string             `json:"displayname"`
	UserType         UserType           `json:"user_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BannedAt         pgtype.Timestamptz `json:"banned_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SessionID        pgtype.Int4        `json:"session_id"`
	SessionPublicID  pgtype.UUID        `json:"session_public_id"`
	SessionKey       pgtype.Text        `json:"session_key"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
}

func (q *Queries) FindAllClientsWithSession(ctx context.Context) ([]FindAllClientsWithSessionRow, error) {
	rows, err := q.db.Query(ctx, findAllClientsWithSession)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllClientsWithSessionRow
	for rows.Next() {
		var i FindAllClientsWithSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Displayname,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BannedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.SessionPublicID,
			&i.SessionKey,
			&i.SessionExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmailWithExpired = `-- name: FindUserByEmailWithExpired :one
SELECT id, public_id, username, email, password, displayname, user_type, created_at, updated_at, banned_at, deleted_at, expires_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmailWithExpired(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmailWithExpired, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findUserByPublicIdWithSession = `-- name: FindUserByPublicIdWithSession :one
SELECT u.id, u.public_id, u.username, u.email, u.password, u.displayname, u.user_type, u.created_at, u.updated_at, u.banned_at, u.deleted_at, u.expires_at, s.id as session_id, s.public_id as session_public_id, s.session_key, s.expires_at as session_expires_at
FROM users u
LEFT JOIN sessions s ON s.user_id = u.id AND (s.expires_at IS NULL OR s.expires_at > NOW())
WHERE u.public_id = $1 AND (u.expires_at IS NULL OR u.expires_at > NOW()) LIMIT 1
`

type FindUserByPublicIdWithSessionRow struct {
	ID               int32              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Password         []byte             `json:"password"`
	Displayname      string             `json:"displayname"`
	UserType         UserType           `json:"user_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BannedAt         pgtype.Timestamptz `json:"banned_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SessionID        pgtype.Int4        `json:"session_id"`
	SessionPublicID  pgtype.UUID        `json:"session_public_id"`
	SessionKey       pgtype.Text        `json:"session_key"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
}

func (q *Queries) FindUserByPublicIdWithSession(ctx context.Context, publicID pgtype.UUID) (FindUserByPublicIdWithSessionRow, error) {
	row := q.db.QueryRow(ctx, findUserByPublicIdWithSession, publicID)
	var i FindUserByPublicIdWithSessionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Displayname,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.SessionPublicID,
		&i.SessionKey,
		&i.SessionExpiresAt,
	)
	return i, err
}
