[tool.black]
line-length = 88
target-version = ["py313"]
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
  | __pycache__
  | \.eggs
  | \.mypy_cache
)/
'''
