run:
    go run main.go

sqlc-generate:
    sqlc generate

db-host := `grep '^DATABASE_HOST' ../../.env | cut -d'=' -f2`
db-user := `grep '^DATABASE_USERNAME' ../../.env | cut -d'=' -f2`
db-name := `grep '^DATABASE_NAME' ../../.env | cut -d'=' -f2`
db-pass := `grep '^DATABASE_PASSWORD' ../../.env | cut -d'=' -f2`
db-port := `grep '^DATABASE_PORT' ../../.env | cut -d'=' -f2`

migrate-up:
    goose -dir database/migrations postgres "host={{db-host}} user={{db-user}} dbname={{db-name}} password={{db-pass}} port={{db-port}} sslmode=require" up

migrate-reset:
    goose -dir database/migrations postgres "host={{db-host}} user={{db-user}} dbname={{db-name}} password={{db-pass}} port={{db-port}} sslmode=require" reset

migrate-status:
    goose -dir database/migrations postgres "host={{db-host}} user={{db-user}} dbname={{db-name}} password={{db-pass}} port={{db-port}} sslmode=require" status
